### ISSUE TITLE
エントリースクリプト

### ISSUE THREAD

**Issue by taityo** [XMLPro/atam#11]
atamのエントリースクリプトを作成する。
一番最初に実行されるプログラムで、ここからサブコマンドの実行ファイルを呼び出す。
※サブコマンドを作成する場合は、必ずここに記述が必要。
※Commander.jsを使用していく。

**Comment by ctare** [comment]
#9 これと被ってる・・・？

**Comment by non258** [comment]
このIssue不要だと思うのですが削除してもいいですか？

**Comment by ctare** [comment]
いいとおもう

**Comment by non258** [comment]
不要なので削除します。
