### ISSUE TITLE
結果の表示

### ISSUE THREAD

**Issue by Inazuma110** [XMLPro/atam#55]
提出結果の表示
#17 を使う

**Comment by Inazuma110** [comment]
提出の結果はターミナルに出力する予定でしたが、ジャッジ中ターミナルを操作できなくなるのは不便に思えるので、こんな感じに通知してくれるようにしようと思うのですが問題ないですか?

![image](https://user-images.githubusercontent.com/31335755/46479039-2b45a900-c829-11e8-9502-001151ca4996.png)

**Comment by non258** [comment]
すごくいいとおもいます！

**Comment by ctare** [comment]
良さげ
