### ISSUE TITLE
Should be contest number optional?

### ISSUE THREAD

**Issue by Tatamo** [XMLPro/atam#59]
たとえば https://beta.atcoder.jp/contests/abs はコンテスト名が"abs"で、コンテスト回数等を表す数字はついていません。
このコンテストに提出するには、 `$atam progam ab s` のような回避策が必要です。
第三引数の「コンテスト回数」は省略可能にしても良いのではないでしょうか。

**Comment by non258** [comment]
コンテスト回数等を表す数字がついてない場合の回避策は必要なので省略可能にしたいと思います。

省略された場合複数該当するコンテストがある場合に、言語選択や問題選択のように検索にて候補を選択できるようにできると良いと思うのですがどうでしょうか。

**Comment by Inazuma110** [comment]
いいと思います
