### ISSUE TITLE
参照するスタイルガイドの決定

### ISSUE THREAD

**Issue by Inazuma110** [XMLPro/atam#62]
現状、どのスタイルガイドを参照すればいいかわかりません。

個人的には[ここ](https://qiita.com/takeharu/items/dee0972e5f39bfd4d7c8)の

- Google Javascript Style Guide
- Airbnb JavaScript Style Guide
- Node.js Style Guide

がいいのかなと思ってますが、どれがいいのかよくわかってないので最終決定をおまかせしたいです。(もちろん、ここにないものを使ってもいいと思います。)

**Comment by ctare** [comment]
個人的にはAirbnb JavaScript Style Guideに良さげ・・・？
ざっとしか読んでないですが、Node.js Style Guideは最近の構文について言及していないので古めかしさを感じました
Google Javascript Style GuideとAirbnb JavaScript Style Guideはどっちでも良さげですが、ページの雰囲気がおしゃれみたいな

[airbnb eslint](https://qiita.com/bohebohechan/items/0332b557f80150e714de)

**Comment by Inazuma110** [comment]
そういえば有名なスタイルガイドとして、#28 で少し出てきた[Javascript Standard Style](https://standardjs.com/rules.html)もありました。

**Comment by Inazuma110** [comment]
特に他に意見がなければ[Airbnb JavaScript Style Guide](http://mitsuruog.github.io/javascript-style-guide/)にしようと思うのですがどうですか?
