### ISSUE TITLE
提出関数を定義しておく

### ISSUE THREAD

**Issue by ctare** [XMLPro/atam#8]
## 提出する関数
* 引数は、問題番号と問題区分とファイル名・・・？
  + 問題番号と問題区分については #7 を参照
* 実際に提出する処理が完了するのは #7 が終わり次第だと思うけど、url固定とか、パラメータ固定とかそんな感じで作っておくと良さげ
  + パラメータに関しても #7 で特定してくれると思う
  + 一先ずは、あとはリンク踏むだけ！みたいなとこまで作っておくと良さげ
* 提出するファイルの読み込みもここでやってしまおう

**Comment by ctare** [comment]
進捗どうですか

**Comment by taityo** [comment]
正直まだ取り掛かれてない感じですね。

**Comment by ctare** [comment]
作業するのが難しそうなら、アサイン取り消してー
進み始めてるのに滞ってしまうのもったいないから、無理なら無理と言ってねー
