### ISSUE TITLE
通知がうまく動かない

### ISSUE THREAD

**Issue by Inazuma110** [XMLPro/atam#89]
僕の環境だけなのかわかりませんが、提出後の通知がうまく動きません。
僕の環境がおかしいか、それとも最近のAtCoderのページ改修が原因だと思いますが、うまく通知が動くでしょうか?
![image](https://user-images.githubusercontent.com/31335755/57997440-99fd1b80-7b07-11e9-9ff0-897af81d1d6d.png)
(無限にターミナルにエラーコードが出てくるためすぐにプロセスをkillしています)

ちなみにソースコードの提出まではうまくいっているようです。

**Comment by ctare** [comment]
まーじされたので閉じます
